### ISSUE TITLE
feat: Add ability to input a completely custom agent configuration to chart

### ISSUE THREAD

**Issue by hawksight** [jetstack/jetstack-secure#418]
Currently the config section is written to be helpful and auto template the required yaml based on either default or a list of resources. [See here](https://github.com/jetstack/jetstack-secure/blob/master/deploy/charts/jetstack-agent/values.yaml#L74-L85).

```yaml
# Configuration section for the agent itself
config:
  # Can override the server if using a proxy between agent and Jetstack Secure
  server: "https://platform.jetstack.io"
  # REQUIRED - Your Jetstack Secure Organisation Name
  organisation: ""
  # REQUIRED - Your Jetstack Secure Cluster Name
  cluster: ""
  period: "0h1m0s"
  dataGatherers:
    default: true
    custom: []
```

If we need to customise this to say namespaces for certain resource, that isn't currently possible.

A better trade of might be to just provide an option to use a customer configmap, or embed the entire config file and ignore the presets.
