### ISSUE TITLE
Deprecated API versions

### ISSUE THREAD

**Issue by hawksight** [jetstack/jetstack-secure#463]
## Problem

It seems like we are using a deprecated apiVersion for `CronJobs`:

```yaml
  - kind: "k8s-dynamic"
    name: "k8s/cronjobs"
    config:
      resource-type:
        version: v1beta1
        resource: cronjobs
        group: batch
```

I got this warning from GKE that it needs to be migrated. Cluster is on 1.27 k8s

![image](https://github.com/jetstack/jetstack-secure/assets/11051419/daa40881-afa1-4d86-8d0e-b09b7f11b577)

This is the case for:
- The `jsctl` install method - promoted by the TLSPK UI currently
- The helm chart in this repo. (as it was based on the above).

To validate, run this and scan through:

```shell
jsctl clusters connect example --stdout | yq ea 'select(.kind == "ConfigMap") .data["config.yaml"]' - | yq
```

And see [here](https://github.com/jetstack/jetstack-secure/blob/master/deploy/charts/jetstack-agent/templates/configmap.yaml#L67C1-L73C23).

## What should had happened?

Fix this.

## Possible fixes

Update the apiVersion? to `v1`

```shell
> k api-resources | grep cronjob
cronjobs                          cj                  batch/v1                               true         CronJob

```
