### ISSUE TITLE
Include clientId in agent log output

### ISSUE THREAD

**Issue by hawksight** [jetstack/jetstack-secure#549]
We seem to dump all the config out when the agent starts up in Venafi Kubernetes Agent. This is useful for debugging.
But we are missing one important piece when connecting to TLSPK on VCP, the `client-id`.

This is passed in the deployment rather than config here:

```yaml
    spec:
      containers:
      - args:
        - agent
        - -c
        - /etc/venafi/agent/config/config.yaml
        - --client-id
        - XXXXX-f707-11ee-922c-XXXXXXX
        - -p
        - 0h1m0s
        - --venafi-cloud
        - --enable-metrics
```

It would be useful to also have this logged on startup.
